### ISSUE TITLE
mouse.py and evdev-mouse.py not working

### ISSUE THREAD

**Issue by Olifiers** [pimoroni/trackball-python#2]
Hi there! The documentation is a bit sparse, so on a fresh Raspbian install neither mouse.py nor evdev-mouse.py run. It would be useful to add the following notes to the docs:

For mouse.py to work, xautomation is required:
sudo apt-get install xautomation

For evdev-mouse.py to work, Python evdev is required:
sudo pip install evdev

A further issue is that, once these requirements are installed, mouse.py fails to compile with a wrong 'maths' statement on line 4. I'm not a Python programmer so can't be of much help on this, unfortunately.

**Comment by Gadgetoid** [comment]
Thank you - I caught the bug in `mouse.py` this morning and made a number of fixes to it a3a4fc6727f7557fcdb3558d4f9a33d4bd4cd638

I've also added a README.md into the examples folder which hopefully clarifies the examples and their requirements - https://github.com/pimoroni/trackball-python/tree/master/examples

**Comment by Olifiers** [comment]
Ace, thanks so much for the prompt and diligent help!!! You folks rock!
